"""initial schema

Revision ID: 6b46b667cec6
Revises: 
Create Date: 2026-03-29 05:58:40.961970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b46b667cec6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bottles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producer', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('beverage_type', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('variety', sa.String(length=200), nullable=True),
    sa.Column('vineyard', sa.String(length=200), nullable=True),
    sa.Column('style', sa.String(length=100), nullable=True),
    sa.Column('age_statement', sa.Integer(), nullable=True),
    sa.Column('proof', sa.Float(), nullable=True),
    sa.Column('mash_bill', sa.String(length=500), nullable=True),
    sa.Column('barrel_type', sa.String(length=200), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('bottle_number', sa.String(length=100), nullable=True),
    sa.Column('bottle_opened_date', sa.String(length=50), nullable=True),
    sa.Column('abv', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('purchase_source', sa.String(length=200), nullable=True),
    sa.Column('purchase_link', sa.String(length=500), nullable=True),
    sa.Column('inventory', sa.Integer(), nullable=False),
    sa.Column('buy', sa.Integer(), nullable=False),
    sa.Column('stars', sa.String(length=50), nullable=True),
    sa.Column('value_for_money', sa.Float(), nullable=True),
    sa.Column('points', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.Column('enriched', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('label_image_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producer', 'name', 'year', 'type', name='uq_bottle_identity')
    )
    op.create_table('cocktails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_cocktail_id', sa.Integer(), nullable=True),
    sa.Column('garnish', sa.String(length=200), nullable=True),
    sa.Column('glassware', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('serving_size', sa.Integer(), nullable=False),
    sa.Column('stars', sa.String(length=50), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_cocktail_id'], ['cocktails.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('beverage_type', sa.String(length=20), nullable=False),
    sa.Column('is_blind', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('host_name', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('event_mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('volume_ml', sa.Integer(), nullable=True),
    sa.Column('abv', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('label_image_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['ingredients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cocktail_instructions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cocktail_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cocktail_tastings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cocktail_id', sa.Integer(), nullable=False),
    sa.Column('recipe_name', sa.String(length=200), nullable=False),
    sa.Column('taster_name', sa.String(length=100), nullable=False),
    sa.Column('tasting_date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('bartender', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_bottles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('bottle_id', sa.Integer(), nullable=False),
    sa.Column('bottle_name', sa.String(length=300), nullable=False),
    sa.Column('blind_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bottle_id'], ['bottles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_cocktails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('cocktail_name', sa.String(length=200), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('bartender', sa.String(length=100), nullable=True),
    sa.Column('blind_number', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['cocktails.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cocktail_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasting_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bottle_id', sa.Integer(), nullable=False),
    sa.Column('bottle_name', sa.String(length=300), nullable=False),
    sa.Column('taster_name', sa.String(length=100), nullable=False),
    sa.Column('tasting_date', sa.Date(), nullable=False),
    sa.Column('beverage_type', sa.String(length=10), nullable=False),
    sa.Column('wine_appearance', sa.Float(), nullable=True),
    sa.Column('wine_aroma', sa.Float(), nullable=True),
    sa.Column('wine_taste', sa.Float(), nullable=True),
    sa.Column('wine_aftertaste', sa.Float(), nullable=True),
    sa.Column('wine_overall', sa.Float(), nullable=True),
    sa.Column('whiskey_nose', sa.Float(), nullable=True),
    sa.Column('whiskey_palate', sa.Float(), nullable=True),
    sa.Column('whiskey_finish', sa.Float(), nullable=True),
    sa.Column('whiskey_overall', sa.Float(), nullable=True),
    sa.Column('appearance_notes', sa.JSON(), nullable=True),
    sa.Column('nose_notes', sa.JSON(), nullable=True),
    sa.Column('palate_notes', sa.JSON(), nullable=True),
    sa.Column('finish_notes', sa.JSON(), nullable=True),
    sa.Column('overall_notes', sa.Text(), nullable=True),
    sa.Column('days_from_crack', sa.Integer(), nullable=True),
    sa.Column('fill_level', sa.Integer(), nullable=True),
    sa.Column('place', sa.String(length=200), nullable=True),
    sa.Column('theme', sa.String(length=200), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bottle_id'], ['bottles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cocktail_tasting_ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cocktail_tasting_id', sa.Integer(), nullable=False),
    sa.Column('recipe_ingredient', sa.String(length=200), nullable=False),
    sa.Column('actual_product', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['cocktail_tasting_id'], ['cocktail_tastings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_cocktail_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('participant_id', sa.String(length=36), nullable=False),
    sa.Column('cocktail_name', sa.String(length=200), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['event_participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_tastings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('participant_id', sa.String(length=36), nullable=False),
    sa.Column('bottle_id', sa.Integer(), nullable=False),
    sa.Column('tasting_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['bottle_id'], ['bottles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['event_participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_tastings')
    op.drop_table('event_cocktail_ratings')
    op.drop_table('cocktail_tasting_ingredients')
    op.drop_table('tasting_notes')
    op.drop_table('recipe_ingredients')
    op.drop_table('event_participants')
    op.drop_table('event_cocktails')
    op.drop_table('event_bottles')
    op.drop_table('cocktail_tastings')
    op.drop_table('cocktail_instructions')
    op.drop_table('ingredients')
    op.drop_table('events')
    op.drop_table('cocktails')
    op.drop_table('bottles')
    # ### end Alembic commands ###
