"""Abstract repository interfaces using Protocol for duck typing.

These protocols define the contract that any storage backend must implement.
The SQLite implementations are the default, but anyone can swap in PostgreSQL,
MongoDB, or any other backend by implementing these protocols.
"""

from typing import Optional, Protocol, TypeVar

T = TypeVar("T")


class BottleRepositoryProtocol(Protocol):
    """Interface for bottle storage operations."""

    def get_by_id(self, bottle_id: int) -> Optional["BottleMetadata"]: ...
    def get_all(self, beverage_type: str | None = None) -> list["BottleMetadata"]: ...
    def create(self, bottle: "BottleMetadata") -> "BottleMetadata": ...
    def update(self, bottle_id: int, bottle: "BottleMetadata") -> "BottleMetadata": ...
    def delete(self, bottle_id: int) -> bool: ...
    def search(self, query: str) -> list["BottleMetadata"]: ...
    def find_duplicates(
        self, producer: str, name: str, year: int | None = None
    ) -> list["BottleMetadata"]: ...


class TastingRepositoryProtocol(Protocol):
    """Interface for tasting note storage operations."""

    def get_by_id(self, tasting_id: int) -> Optional["TastingNote"]: ...
    def get_by_bottle_id(self, bottle_id: int) -> list["TastingNote"]: ...
    def create(self, tasting: "TastingNote", bottle_id: int) -> "TastingNote": ...
    def delete(self, tasting_id: int) -> bool: ...
    def get_summary_for_bottle(self, bottle_id: int) -> dict: ...


class CocktailRepositoryProtocol(Protocol):
    """Interface for cocktail recipe storage operations."""

    def get_by_id(self, cocktail_id: int) -> Optional["CocktailRecipe"]: ...
    def get_all(self) -> list["CocktailRecipe"]: ...
    def create(self, cocktail: "CocktailRecipe") -> "CocktailRecipe": ...
    def update(self, cocktail_id: int, cocktail: "CocktailRecipe") -> "CocktailRecipe": ...
    def delete(self, cocktail_id: int) -> bool: ...
    def search(self, query: str) -> list["CocktailRecipe"]: ...


class CocktailTastingRepositoryProtocol(Protocol):
    """Interface for cocktail tasting storage operations."""

    def get_by_cocktail_id(self, cocktail_id: int) -> list["CocktailTastingNote"]: ...
    def create(
        self, tasting: "CocktailTastingNote", cocktail_id: int
    ) -> "CocktailTastingNote": ...
    def delete(self, tasting_id: int) -> bool: ...


class IngredientRepositoryProtocol(Protocol):
    """Interface for ingredient storage operations."""

    def get_by_id(self, ingredient_id: int) -> Optional["Ingredient"]: ...
    def get_all(self) -> list["Ingredient"]: ...
    def get_tree(self) -> list["Ingredient"]: ...
    def get_by_name(self, name: str) -> Optional["Ingredient"]: ...
    def get_descendants(self, ingredient_id: int) -> list["Ingredient"]: ...
    def create(self, ingredient: "Ingredient") -> "Ingredient": ...
    def update(self, ingredient_id: int, ingredient: "Ingredient") -> "Ingredient": ...
    def delete(self, ingredient_id: int) -> bool: ...


class EventRepositoryProtocol(Protocol):
    """Interface for event storage operations."""

    def get_by_id(self, event_id: str) -> Optional[dict]: ...
    def get_all(self) -> list[dict]: ...
    def create(self, event_data: dict) -> dict: ...
    def update(self, event_id: str, event_data: dict) -> dict: ...
    def delete(self, event_id: str) -> bool: ...
    def add_participant(self, event_id: str, participant_data: dict) -> dict: ...
    def add_tasting(self, participant_id: str, tasting_data: dict) -> dict: ...
    def update_status(self, event_id: str, status: str) -> dict: ...
